name: adgrid

services:
  postgres:
    image: postgres:16-alpine
    container_name: adgrid-postgres
    environment:
      POSTGRES_USER: adgrid_admin
      POSTGRES_PASSWORD: adgrid_local_dev
      POSTGRES_DB: adgrid
    ports:
      - "55433:5432"
    volumes:
      - adgrid-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adgrid_admin -d adgrid"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: adgrid-redis
    ports:
      - "56379:6379"

volumes:
  adgrid-pgdata:
